TeachAssist/Models/Classroom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Models
{
    public class Classroom
    {
        public int Id { get; set; }
        public Widget[] Widgets { get; set; }

        public void LoadClassroom(int ID)
        {
            this.Id = ID;

            // Temporary code.  Delete after finishing real code
            fakeLoadClassroom();

            // Connect to DB and load Classroom data for ID

        }

        public void SaveClassroom()
        {
            // Save the currently loaded widgets to the DB with current ID
        }

        private void fakeLoadClassroom()
        {
            Widgets = new Widget[4];
            Widget widgetOne = new Widget(0, "Widget 1", 1, 1);
            Widget widgetTwo = new Widget(1, "Widget 2", 1, 1);
            Widget widgetThree = new Widget(2, "Widget 3", 1, 1);
            Widget widgetFour = new Widget(3, "Widget 4", 1, 1);

            Widgets[0] = widgetOne;
            Widgets[1] = widgetTwo;
            Widgets[2] = widgetThree;
            Widgets[3] = widgetFour;
        }
    }
}

TeachAssist/Models/ErrorViewModel.cs
using System;

namespace TeachAssist.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TeachAssist/Models/UserAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeachAssist.Models;

namespace TeachAssist.Models
{
    public class UserAccount
    {
        public Classroom[] Classrooms { get; set; }


    }
}

TeachAssist/Models/Widget.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeachAssist.Models;

namespace TeachAssist.Models
{
    public class Widget
    {
        public int Id { get;}
        public string Name { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public WidgetCreationHelper[] WidgetCreationHelpers { get; set; }

        public Widget(int id, string name, int width, int height)
        {
            this.Id = id;
            this.Name = name;
            this.Width = width;
            this.Height = height;
        }

    }
}

TeachAssist/Models/WidgetCreationFunction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Models
{
    public class WidgetCreationFunction : WidgetCreationHelper
    {
    }
}

TeachAssist/Models/WidgetCreationGraph.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Models
{
    public class WidgetCreationGraph : WidgetCreationHelper
    {
    }
}

TeachAssist/Models/WidgetCreationHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Models
{
    public class WidgetCreationHelper
    {
        public int id { get; set; }
        public string img { get; set; }
        public int xcoordinate { get; set; }
        public int ycoordinate { get; set; }
    }
}

TeachAssist/Models/WidgetCreationSource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Models
{
    public class WidgetCreationSource : WidgetCreationHelper
    {
        public int sourceID { get; set; }
    }
}

TeachAssist/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TeachAssist/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeachAssist.Models;

namespace TeachAssist.Controllers
{
    public class DashboardController : Controller
    {
        Classroom classroom = new Classroom();
        public IActionResult Index()
        {

            classroom.LoadClassroom(0);
            return View();
        }

        /*
        public IActionResult Index(int classroomNum)
        {
            classroom.LoadClassroom(classroomNum);
            return View();
        }
        */
    }
}

TeachAssist/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TeachAssist.Models;

namespace TeachAssist.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeachAssist/Controllers/SignInController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeachAssist.Controllers
{
    public class SignInController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TeachAssist/Controllers/WidgetEditorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeachAssist.Models;

namespace TeachAssist.Controllers
{
    public class WidgetEditorController : Controller
    {
        Widget widget = new Widget(0, "New Widget", 0, 0);

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult SaveWidget()
        {
            ViewBag.Message = "Widget Saved!";
            return View();
        }

        public ActionResult DeleteWidget()
        {
            ViewBag.Message = "Widget Deleted.";
            return View();
        }
    }
}

TeachAssist/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}


@section Scripts {

    <script src="~/js/JQuery/jquery-1.12.4.js"></script>
    <script src="~/js/JQuery/jquery-ui.js"></script>
    <script src="~/js/JQuery/Plugins/jsPlumb.min.js"></script>
    <script src="~/js/JQuery/Plugins/jquery.canvasjs.min.js"></script>
    <script src="~/js/JQuery/Plugins/AppendGrid.js"></script>

    <script>
        //Drag and drop elements from the sidebar code

        //Global variables for ID iteration on html elements
        $table_iteration = 0;
        $widget_iteration = 0;
        var myAppendGrid = [];
        var tables = [];
        var widgetHelpers = [];

        jsPlumb.setContainer($("body"));

        jsPlumb.ready(function () {
            // jsPlumb.bind("connection", updateWidgets());
            // Make Widget helpers draggable
            $(".sidebar_widget_helper").draggable(
                {
                    helper: "clone",
                    revert: "invalid",
                    appendTo: "#widget-grid-area",
                    cursor: "move",
                    drag: function () {
                        jsPlumb.repaintEverything();
                    },
                    start: function () {
                        console.log("dragging");
                    },
                    stop: function () {
                        console.log('stopped');
                    },
                }
            );

            // Make the Widget editor area droppable
            $("#widget-grid-area").droppable(
                {
                    accept: ".sidebar_widget_helper",
                    drop: function (event, ui) {
                        // Make Widget Helper Clones
                        if (ui.draggable.hasClass("sidebar_widget_helper")) {
                            // Set Appropriate Widget ID
                            var $WidgetID = ui.draggable.attr('id') + "-" + $widget_iteration;
                            widgetHelpers.push($WidgetID);
                            var $item = $(ui.draggable).clone().attr('id', $WidgetID).appendTo("#widget-grid-area").css(
                                {
                                    position: 'absolute',
                                }
                            );
                            $item.addClass("widget_editor_widget_helper");
                            $widget_iteration++;

                            $item.removeClass("sidebar_widget_helper");
                            makeDraggable($item);

                            // When Item is hovered over, change class
                            $item.hover(function () {
                                $(this).toggleClass('active');
                                console.log("ID: " + $(".active").attr('id'));
                            });
                        }
                    }
                }
            )
        });

        function fillFunction(id, source) {
            // Select DropDown Menu
            var DropDownList = document.getElementById(id).getElementsByTagName('select');

            // Grab Columns from source
            // var columns = getColumnNamesFromTableID(source);

            var columns = ["Grades"];

            // Remove All dropdowns and append Column names to drop down list
            for (var i = 0; i < columns.length; i++) {
                console.log("Column " + i + ": " + columns[i]);
                var option = document.createElement("option");
                option.text = columns[i];
                DropDownList[0].add(option);
            }
        }

        function fillGraph() {
            // Get Source Data

            // Get Function and create values
            var labels = ["A", "B", "D"];
            var values = [2, 1, 1];
            var average = "B"

            // Send values to createGraph function
            createBarGraph("widget-1", "Average Grade: " + average, labels, values);
        }

        function createBarGraph(id, graphTitle, labels, values) {
            var barGraph = new CanvasJS.Chart(id, {
                theme: "light1",
                animationEnabled: false,
                title: {
                    text: graphTitle
                },
                data: [
                    {
                        type: "column",
                        dataPoints: [
                        ]
                    }
                ]
            });

            barGraph.render();

            for (var i = 0; i < labels.length; i++) {
                barGraph.data[0].addTo("dataPoints", { y: values[i], label: labels[i] });
            }

            barGraph.render();
        }

        // ----------- Helper Functions ------------------
        // Make Widget Draggable
        function makeDraggable($item) {
            $item.draggable({
                cursor: "move",
                grid: [20, 20],
                containment: "#widget-grid-area",
                drag: function () {
                    jsPlumb.repaintEverything();
                    //console.log("jsplumb repainting");
                },
                start: function () { },
                stop: function () {
                    console.log('stopped')
                }
            });
        }
    </script>

}

<div id="action-menu">

    <button id="new_widget_btn" onclick="window.location = '@Url.Action("Index", "WidgetEditor")'">New Widget</button>
    <button id="save_classroom_btn">Save Classroom</button>
    <button id="load_classroom_btn">Load Classroom</button>
</div>
<div id="dashboard">
    <div id="widget-grid-area">

    </div>
    <div id="widget-selection-menu">
        <h1>Saved Widgets</h1>
        <div class="sidebar_widget_helper" id="widget-1" onload="fillGraph()">
            <!-- <img src="~/Images/piechart.png" alt="pieChart_btn"> -->
            <h1 class="widget_helper_heading">Widget-1</h1>
            <div class="widget_helper_graph_output"></div>
        </div>
    </div>
</div>

TeachAssist/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Teach-Assist!</h1>
    <p>The sign-in is not working yet, so click the Teach-Assist logo in the top left.</p>
</div>

TeachAssist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeachAssist</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index"> <img src="~/Images/TeachASSIST_Logo_1.png" alt="TeachAssist" width="322" height="79"> <i style="font-size: 10px">grading made easy</i></a>
            </div>
            <div class="user-menu">
                <button id="user-account-btn" onclick="window.location = '@Url.Action("Index", "Account")'">pinkhamm</button>
                <button id="user-settings-btn" onclick="window.location = '@Url.Action("Index", "Account")'"><img id="user-settings-icon" src="~/Images/user-settings-icon.png" alt="Account Settings"></button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TeachAssist - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TeachAssist/Views/SignIn/Index.cshtml
@{
    ViewData["Title"] = "SignIn";
}